const khronos = 'KhronosGroup/glTF-Sample-Assets';
const branch = 'main';
const commitSha = '2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf';
const CDN_MAX_SIZE = 20 * 1024 * 1024;

const chineseNames = {
  'car-concept': '概念跑车',
  'toy-car': '玩具汽车',
  'fire-truck': '消防车',
  'steam-locomotive': '蒸汽机车',
  'vehicle-drivetrain': '汽车传动总成',
  'racing-motorcycle': '越野摩托车',
  'green-racing-truck': '绿色越野卡车',
  'trackside-camp': '赛道营地',
  'bath-day': '沐浴日微场景',
  'space-ship-hallway': '太空飞船走廊',
  'space-lander-a': '太空登陆器 A',
  'space-transport-truck': '太空运输车',
  'solar-panel': '太阳能板组件',
  'detailed-satellite-dish': '详细卫星天线',
  'space-rover': '太空探测车',
  'space-generator': '太空发电机',
  'space-mining-craft': '太空采矿飞船',
  'corner-computer-workstation': '转角电脑工作站',
  'wireless-machine-cable': '无线设备与线缆',
  'cargo-monorail-train': '货运单轨列车',
  'large-space-hangar': '大型太空机库',
  'space-office-chair': '太空办公椅',
  'compact-laptop': '轻薄笔记本电脑',
  'wooden-radio': '复古木质收音机',
  'tractor-shovel': '铲斗拖拉机',
  'stacked-washer-dryer': '叠放式洗衣烘干机',
  'modern-ceiling-fan': '现代吊扇',
  'design-lounge-sofa': '设计休闲沙发',
  'race-finish-gantry': '赛道终点门架',
  'flying-mechanical-drone': '悬浮机械无人机',
  'falling-mechanism-platform': '坠落机关平台',
  'platformer-robot': '平台跳跃机器人',
  'coin-question-block': '金币问号方块',
  'round-grass-platform': '圆形草地平台',
  'armchair-with-pillows': '软垫扶手椅',
  'standing-lamp': '落地灯',
  'space-mining-drill': '太空采矿钻机',
  'primary-ion-drive': '初级离子推进器',
  'city-sedan': '城市轿车',
  'freestanding-oven': '独立烤箱',
  'tall-wind-turbine': '高塔风力发电机',
  'city-garage': '城市车库',
  'city-house': '小型城市住宅',
  'city-fountain': '城市喷泉',
  'road-lightposts': '双路灯直道路段',
  'arena-statue': '竞技场雕像',
  'arena-wall-gate': '竞技场城门',
  'low-poly-pine-tree': '低多边形松树',
  'arena-trophy': '竞技奖杯',
  'antique-camera': '古董相机',
  'steampunk-camera': '蒸汽朋克相机',
  'chronograph-watch': '计时腕表',
  'boom-box': '便携音响',
  'vintage-television': '复古电视机',
  'countertop-coffee-machine': '台式咖啡机与杯子',
  'commercial-refrigerator': '商用冰箱',
  'water-bottle': '运动水瓶',
  'materials-variants-shoe': '多材质运动鞋',
  'cesium-milk-truck': '牛奶运输车',
  'sunglasses-khronos': '太阳镜',
  'anisotropy-barn-lamp': '各向异性谷仓灯',
  'iridescence-lamp': '虹彩台灯',
  'punctual-light-lamp': '点光源台灯',
  'stained-glass-lamp': '彩色玻璃台灯',
  lantern: '街灯',
  'chair-damask': '紫金花纹椅',
  'glam-velvet-sofa': '丝绒沙发',
  'sheen-chair': '光泽单椅',
  'wood-leather-sofa': '木质皮革沙发',
  'silk-pouf': '丝绸软凳',
  'glass-vase-flowers': '玻璃花瓶与鲜花',
  'hurricane-candle-holder': '玻璃烛台',
  'broken-window': '破损玻璃窗',
  'transmission-plant': '半透明绿植',
  corset: '紧身胸衣',
  avocado: '牛油果',
  'barramundi-fish': '金目鲈',
  'transmission-teacup': '半透明茶杯',
  'iridescent-dish': '虹彩橄榄餐盘',
  'iridescence-abalone': '虹彩鲍鱼摆件',
  'mosquito-in-amber': '琥珀蚊虫摆件',
  'a-beautiful-game': '精致国际象棋',
  'sheen-cloth': '光泽织物',
  'carbon-fibre': '碳纤维材质',
  'clear-coat-car-paint': '清漆车漆材质',
  'clearcoat-wicker': '清漆藤编材质球',
  'usd-shader-ball': 'USD 材质球',
  fox: '动画狐狸',
  'pot-of-coals': '炭火盆',
};

function asset({ id, name, category, path, size, license = '逐资产许可', attribution = '请在模型目录的 LICENSE.md 中核验作者、署名和商用要求。', riskNote = '', tosUrl = null, packageUrl = null, originalSourceUrl = null, repo = khronos, branchName = branch, commit = commitSha, stars = 993, updated = '2026', description = null, licenseUrl = null }) {
  const encodedPath = path.split('/').map(encodeURIComponent).join('/');
  const modelDirectory = encodeURIComponent(path.split('/')[1]);
  const githubRawUrl = `https://raw.githubusercontent.com/${repo}/${commit}/${encodedPath}`;
  const useCdn = size <= CDN_MAX_SIZE;
  const deliveryUrl = useCdn ? `https://cdn.jsdelivr.net/gh/${repo}@${commit}/${encodedPath}` : githubRawUrl;
  return {
    id,
    name: chineseNames[id] || name,
    nameEn: name,
    category,
    format: path.toLowerCase().endsWith('.glb') ? 'GLB' : 'glTF',
    path,
    size,
    license,
    attribution,
    riskNote,
    repo,
    branch: branchName,
    commitSha: commit,
    stars,
    updated,
    description: description || 'Khronos glTF Sample Assets 中的真实模型文件。',
    rawUrl: tosUrl || deliveryUrl,
    fallbackUrl: tosUrl ? deliveryUrl : githubRawUrl,
    githubRawUrl,
    tosUrl,
    packageUrl,
    originalSourceUrl,
    delivery: tosUrl ? '妙笔 TOS' : (useCdn ? 'jsDelivr CDN' : 'GitHub Raw'),
    sourceUrl: `https://github.com/${repo}/blob/${commit}/${encodedPath}`,
    repoUrl: `https://github.com/${repo}`,
    licenseUrl: licenseUrl || `https://github.com/${repo}/blob/${commit}/Models/${modelDirectory}/LICENSE.md`,
    trusted: true,
  };
}

export const curatedAssets = [
  asset({
    id: 'car-concept',
    name: 'Car Concept',
    category: '汽车',
    path: 'Models/CarConcept/GLB/CarConcept.glb',
    size: 10267996,
    license: 'CC BY 4.0 + 商标说明',
    attribution: 'Eric Chadwick / DGG；含 Khronos 与 3D Commerce 标志。',
    riskNote: '模型包含 Khronos 与 3D Commerce 标志，商标权不随 CC BY 4.0 授予；保留 GitHub 来源，不迁移到本库 TOS。',
  }),
  asset({
    id: 'toy-car',
    name: 'Toy Car',
    category: '汽车',
    path: 'Models/ToyCar/glTF-Binary/ToyCar.glb',
    size: 5422412,
    license: 'CC0 1.0',
    attribution: 'Guido Odendahl / Eric Chadwick。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/toy-car.glb',
  }),
  asset({
    id: 'fire-truck',
    name: 'Fire Truck',
    category: '汽车',
    path: 'vendor/kenney/car-kit/Models/GLB format/firetruck.glb',
    size: 232448,
    license: 'CC0 1.0',
    attribution: 'Kenney / Car Kit；CC0 无强制署名。',
    riskNote: '通用低多边形消防车，无可见文字或 Logo；CC0 不涉及商标授权。完整包包含 GLB 与共享色板纹理。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2026-07-13',
    description: 'GitHub 固定镜像中保留原始 Kenney Car Kit 许可的 CC0 低多边形消防车。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/car-kit/License.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/fire-truck/firetruck.glb',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/fire-truck/fire-truck-complete.zip',
  }),
  asset({
    id: 'steam-locomotive',
    name: 'Steam Locomotive',
    category: '机械',
    path: 'vendor/kenney/train-kit/Models/GLB format/train-locomotive-a.glb',
    size: 154620,
    license: 'CC0 1.0',
    attribution: 'Kenney；Guus Vermeulen、Tony Schaer / Train Kit。',
    riskNote: '通用低多边形蒸汽机车，无可见文字或 Logo；CC0 不涉及商标授权。完整包包含 GLB 与共享色板纹理。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2026-07-13',
    description: 'GitHub 固定镜像中保留原始 Kenney Train Kit 许可的 CC0 蒸汽机车。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/train-kit/License.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/steam-locomotive/train-locomotive-a.glb',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/steam-locomotive/steam-locomotive-complete.zip',
  }),
  asset({
    id: 'vehicle-drivetrain',
    name: 'Vehicle Drivetrain',
    category: '机械',
    path: 'vendor/kenney/car-kit/Models/GLB format/debris-drivetrain.glb',
    size: 36896,
    license: 'CC0 1.0',
    attribution: 'Kenney / Car Kit；CC0 无强制署名。',
    riskNote: '原文件以 debris 命名，是通用低多边形传动构件而非工程级 CAD；无可见文字或 Logo。完整包包含 GLB 与共享色板纹理。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2026-07-13',
    description: 'GitHub 固定镜像中保留原始 Kenney Car Kit 许可的 CC0 汽车传动构件。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/car-kit/License.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vehicle-drivetrain/debris-drivetrain.glb',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vehicle-drivetrain/vehicle-drivetrain-complete.zip',
  }),
  asset({
    id: 'racing-motorcycle',
    name: 'Racing Motorcycle',
    category: '汽车',
    path: 'models/vehicle-motorcycle.glb',
    size: 97172,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit Racing 3D 模型以 CC0 发布。',
    riskNote: '低多边形风格，无品牌标识。',
    repo: 'KenneyNL/Starter-Kit-Racing',
    branchName: 'main',
    commit: 'f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc',
    stars: 366,
    updated: '2026-03-31',
    description: 'Kenney Starter Kit Racing 中的 CC0 低多边形赛车素材。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-Racing/blob/f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-racing/f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc/racing-motorcycle.glb',
  }),
  asset({
    id: 'green-racing-truck',
    name: 'Green Racing Truck',
    category: '汽车',
    path: 'models/vehicle-truck-green.glb',
    size: 104228,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit Racing 3D 模型以 CC0 发布。',
    riskNote: '低多边形风格，无品牌标识。',
    repo: 'KenneyNL/Starter-Kit-Racing',
    branchName: 'main',
    commit: 'f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc',
    stars: 366,
    updated: '2026-03-31',
    description: 'Kenney Starter Kit Racing 中的 CC0 低多边形赛车素材。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-Racing/blob/f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-racing/f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc/green-racing-truck.glb',
  }),
  asset({
    id: 'trackside-camp',
    name: 'Trackside Camp',
    category: '场景',
    path: 'models/decoration-tents.glb',
    size: 168004,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit Racing 3D 模型以 CC0 发布。',
    riskNote: '低多边形赛道装饰场景，无品牌标识。',
    repo: 'KenneyNL/Starter-Kit-Racing',
    branchName: 'main',
    commit: 'f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc',
    stars: 366,
    updated: '2026-03-31',
    description: 'Kenney Starter Kit Racing 中的 CC0 赛道营地装饰。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-Racing/blob/f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-racing/f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc/trackside-camp.glb',
  }),
  asset({
    id: 'bath-day',
    name: 'Bath Day',
    category: '场景',
    path: 'examples/models/gltf/bath_day.glb',
    size: 811108,
    license: 'CC BY 4.0',
    attribution: '“Bath day” by StanSt（Sketchfab），使用时需保留 CC BY 4.0 署名与来源。',
    riskNote: '固定 GLB 的 asset.extras 内嵌作者、原始来源和 CC BY 4.0；未发现可见品牌。需要 WebP、Draco、GPU instancing 与 transmission 支持。',
    repo: 'mrdoob/three.js',
    branchName: 'dev',
    commit: '34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8',
    stars: 110000,
    updated: '2026-07-20',
    description: 'Three.js 官方样例仓库中的动画浴室微缩场景。',
    licenseUrl: 'https://github.com/mrdoob/three.js/blob/34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8/examples/models/gltf/bath_day.glb',
    originalSourceUrl: 'https://sketchfab.com/3d-models/bath-day-c1b0d6edd934423d965e3cd032eb358e',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/mrdoob/three.js/34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8/bath-day.glb',
  }),
  asset({
    id: 'space-ship-hallway',
    name: 'Space Ship Hallway',
    category: '场景',
    path: 'examples/models/gltf/space_ship_hallway.glb',
    size: 2896272,
    license: 'CC BY 4.0',
    attribution: '“Space Ship Hallway” by yeeyeeman（Sketchfab），使用时需保留 CC BY 4.0 署名与来源。',
    riskNote: '固定 GLB 的 asset.extras 内嵌作者、原始来源和 CC BY 4.0；原创科幻走廊，无可见现实品牌或 Logo。',
    repo: 'mrdoob/three.js',
    branchName: 'dev',
    commit: '34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8',
    stars: 110000,
    updated: '2026-07-20',
    description: 'Three.js 官方样例仓库中的高细节科幻飞船走廊。',
    licenseUrl: 'https://github.com/mrdoob/three.js/blob/34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8/examples/models/gltf/space_ship_hallway.glb',
    originalSourceUrl: 'https://sketchfab.com/3d-models/space-ship-hallway-e97dce00ae5549a8a3795e06bc2cfc96',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/mrdoob/three.js/34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8/space-ship-hallway.glb',
  }),
  asset({
    id: 'space-lander-a',
    name: 'Space Lander A',
    category: '产品',
    path: 'addons/kaykit_space_base_bits/Assets/gltf/lander_A.gltf',
    size: 110072,
    license: 'CC0 1.0',
    attribution: 'Kay Lousberg / KayKit Space Base Bits；CC0 无强制署名。',
    riskNote: '通用低多边形科幻登陆器，无文字、Logo 或现实品牌元素；完整包包含 glTF、BIN 与共享纹理。',
    repo: 'KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0',
    branchName: 'main',
    commit: '6dfbcac9927d06283752c4defd4882cfe0d29666',
    stars: 9,
    updated: '2023-09-16',
    description: 'KayKit Space Base Bits 中的 CC0 低多边形太空登陆器。',
    licenseUrl: 'https://github.com/KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0/blob/6dfbcac9927d06283752c4defd4882cfe0d29666/LICENSE.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/gltf/lander_A.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/packages/space-lander-a-complete.zip',
  }),
  asset({
    id: 'space-transport-truck',
    name: 'Space Transport Truck',
    category: '汽车',
    path: 'addons/kaykit_space_base_bits/Assets/gltf/spacetruck.gltf',
    size: 86190,
    license: 'CC0 1.0',
    attribution: 'Kay Lousberg / KayKit Space Base Bits；CC0 无强制署名。',
    riskNote: '通用低多边形科幻运输车，无文字、Logo 或现实品牌元素；完整包包含 glTF、BIN 与共享纹理。',
    repo: 'KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0',
    branchName: 'main',
    commit: '6dfbcac9927d06283752c4defd4882cfe0d29666',
    stars: 9,
    updated: '2023-09-16',
    description: 'KayKit Space Base Bits 中的 CC0 低多边形太空运输车。',
    licenseUrl: 'https://github.com/KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0/blob/6dfbcac9927d06283752c4defd4882cfe0d29666/LICENSE.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/gltf/spacetruck.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/packages/space-transport-truck-complete.zip',
  }),
  asset({
    id: 'solar-panel',
    name: 'Solar Panel',
    category: '产品',
    path: 'addons/kaykit_space_base_bits/Assets/gltf/solarpanel.gltf',
    size: 35475,
    license: 'CC0 1.0',
    attribution: 'Kay Lousberg / KayKit Space Base Bits；CC0 无强制署名。',
    riskNote: '通用低多边形太阳能板组件，无文字、Logo 或现实品牌元素；完整包包含 glTF、BIN 与共享纹理。',
    repo: 'KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0',
    branchName: 'main',
    commit: '6dfbcac9927d06283752c4defd4882cfe0d29666',
    stars: 9,
    updated: '2023-09-16',
    description: 'KayKit Space Base Bits 中的 CC0 低多边形太阳能板组件。',
    licenseUrl: 'https://github.com/KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0/blob/6dfbcac9927d06283752c4defd4882cfe0d29666/LICENSE.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/gltf/solarpanel.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/packages/solar-panel-complete.zip',
  }),
  asset({
    id: 'detailed-satellite-dish',
    name: 'Detailed Satellite Dish',
    category: '产品',
    path: 'vendor/kenney/space-kit/Models/GLTF format/satelliteDish_detailed.glb',
    size: 26044,
    license: 'CC0 1.0',
    attribution: 'Kenney / Space Kit；CC0 无强制署名。',
    riskNote: '通用低多边形卫星天线，无可见 Logo 或文字；CC0 不授予商标权。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2020-08-27',
    description: 'GitHub 固定镜像中保留原始 Kenney Space Kit 许可的 CC0 详细卫星天线。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/space-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/space-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/space-kit/satelliteDish_detailed.glb',
  }),
  asset({
    id: 'space-rover',
    name: 'Space Rover',
    category: '汽车',
    path: 'vendor/kenney/space-kit/Models/GLTF format/rover.glb',
    size: 13384,
    license: 'CC0 1.0',
    attribution: 'Kenney / Space Kit；CC0 无强制署名。',
    riskNote: '通用低多边形太空探测车，无可见 Logo、文字或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2020-08-27',
    description: 'GitHub 固定镜像中保留原始 Kenney Space Kit 许可的 CC0 太空探测车。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/space-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/space-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/space-kit/rover.glb',
  }),
  asset({
    id: 'space-generator',
    name: 'Space Generator',
    category: '机械',
    path: 'vendor/kenney/space-kit/Models/GLTF format/machine_generator.glb',
    size: 28044,
    license: 'CC0 1.0',
    attribution: 'Kenney / Space Kit；CC0 无强制署名。',
    riskNote: '通用低多边形发电机与线缆组件，无可见 Logo、文字或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2020-08-27',
    description: 'GitHub 固定镜像中保留原始 Kenney Space Kit 许可的 CC0 太空发电机。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/space-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/space-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/space-kit/machine_generator.glb',
  }),
  asset({
    id: 'space-mining-craft',
    name: 'Space Mining Craft',
    category: '产品',
    path: 'vendor/kenney/space-kit/Models/GLTF format/craft_miner.glb',
    size: 26672,
    license: 'CC0 1.0',
    attribution: 'Kenney / Space Kit；CC0 无强制署名。',
    riskNote: '通用低多边形科幻采矿飞船，无可见 Logo、文字或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2020-08-27',
    description: 'GitHub 固定镜像中保留原始 Kenney Space Kit 许可的 CC0 太空采矿飞船。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/space-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/space-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/space-kit/craft_miner.glb',
  }),
  asset({
    id: 'corner-computer-workstation',
    name: 'Corner Computer Workstation',
    category: '数码',
    path: 'vendor/kenney/space-kit/Models/GLTF format/desk_computerCorner.glb',
    size: 8720,
    license: 'CC0 1.0',
    attribution: 'Kenney / Space Kit；CC0 无强制署名。',
    riskNote: '通用低多边形转角电脑工作站，无屏幕文字、Logo 或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2020-08-27',
    description: 'GitHub 固定镜像中保留原始 Kenney Space Kit 许可的 CC0 转角电脑工作站。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/space-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/space-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/space-kit/desk_computerCorner.glb',
  }),
  asset({
    id: 'wireless-machine-cable',
    name: 'Wireless Machine with Cable',
    category: '机械',
    path: 'vendor/kenney/space-kit/Models/GLTF format/machine_wirelessCable.glb',
    size: 20884,
    license: 'CC0 1.0',
    attribution: 'Kenney / Space Kit；CC0 无强制署名。',
    riskNote: '通用低多边形无线设备与线缆组件，无可见 Logo、文字或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2020-08-27',
    description: 'GitHub 固定镜像中保留原始 Kenney Space Kit 许可的 CC0 无线设备与线缆。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/space-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/space-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/space-kit/machine_wirelessCable.glb',
  }),
  asset({
    id: 'cargo-monorail-train',
    name: 'Cargo Monorail Train',
    category: '汽车',
    path: 'vendor/kenney/space-kit/Models/GLTF format/monorail_trainCargo.glb',
    size: 51296,
    license: 'CC0 1.0',
    attribution: 'Kenney / Space Kit；CC0 无强制署名。',
    riskNote: '通用低多边形货运单轨列车，无可见 Logo、文字或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2020-08-27',
    description: 'GitHub 固定镜像中保留原始 Kenney Space Kit 许可的 CC0 货运单轨列车。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/space-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/space-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/space-kit/monorail_trainCargo.glb',
  }),
  asset({
    id: 'large-space-hangar',
    name: 'Large Space Hangar',
    category: '场景',
    path: 'vendor/kenney/space-kit/Models/GLTF format/hangar_largeA.glb',
    size: 25304,
    license: 'CC0 1.0',
    attribution: 'Kenney / Space Kit；CC0 无强制署名。',
    riskNote: '通用低多边形太空机库场景模块，无可见 Logo、文字或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2020-08-27',
    description: 'GitHub 固定镜像中保留原始 Kenney Space Kit 许可的 CC0 大型太空机库。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/space-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/space-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/space-kit/hangar_largeA.glb',
  }),
  asset({
    id: 'space-office-chair',
    name: 'Space Office Chair',
    category: '家居',
    path: 'vendor/kenney/space-kit/Models/GLTF format/desk_chairArms.glb',
    size: 10440,
    license: 'CC0 1.0',
    attribution: 'Kenney / Space Kit；CC0 无强制署名。',
    riskNote: '通用低多边形扶手办公椅，无可见 Logo、文字或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2020-08-27',
    description: 'GitHub 固定镜像中保留原始 Kenney Space Kit 许可的 CC0 扶手办公椅。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/space-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/space-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/space-kit/desk_chairArms.glb',
  }),
  asset({
    id: 'compact-laptop',
    name: 'Compact Laptop',
    category: '数码',
    path: 'vendor/kenney/furniture-kit/Models/GLTF format/laptop.glb',
    size: 5540,
    license: 'CC0 1.0',
    attribution: 'Kenney / Furniture Kit；CC0 无强制署名。',
    riskNote: '通用低多边形笔记本电脑，无屏幕文字、Logo 或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2018-10-20',
    description: 'GitHub 固定镜像中保留原始 Kenney Furniture Kit 许可的 CC0 轻薄笔记本电脑。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/furniture-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/furniture-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/furniture-kit/laptop.glb',
  }),
  asset({
    id: 'wooden-radio',
    name: 'Wooden Radio',
    category: '数码',
    path: 'vendor/kenney/furniture-kit/Models/GLTF format/radio.glb',
    size: 25020,
    license: 'CC0 1.0',
    attribution: 'Kenney / Furniture Kit；CC0 无强制署名。',
    riskNote: '通用低多边形木质收音机，无刻度文字、Logo 或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2018-10-20',
    description: 'GitHub 固定镜像中保留原始 Kenney Furniture Kit 许可的 CC0 复古木质收音机。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/furniture-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/furniture-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/furniture-kit/radio.glb',
  }),
  asset({
    id: 'tractor-shovel',
    name: 'Tractor Shovel',
    category: '机械',
    path: 'vendor/kenney/car-kit/Models/GLB format/tractor-shovel.glb',
    size: 222584,
    license: 'CC0 1.0',
    attribution: 'Kenney / Car Kit；CC0 无强制署名。',
    riskNote: '通用低多边形铲斗拖拉机，无可见 Logo 或文字；完整包包含 GLB 与共享色板纹理。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2026-04-02',
    description: 'GitHub 固定镜像中保留原始 Kenney Car Kit 许可的 CC0 铲斗拖拉机。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/car-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/car-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/car-kit/tractor-shovel/tractor-shovel.glb',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/car-kit/tractor-shovel/tractor-shovel-complete.zip',
  }),
  asset({
    id: 'stacked-washer-dryer',
    name: 'Stacked Washer Dryer',
    category: '家居',
    path: 'vendor/kenney/furniture-kit/Models/GLTF format/washerDryerStacked.glb',
    size: 64060,
    license: 'CC0 1.0',
    attribution: 'Kenney / Furniture Kit；CC0 无强制署名。',
    riskNote: '通用低多边形洗衣烘干设备，无控制面板文字、Logo 或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2018-10-20',
    description: 'GitHub 固定镜像中保留原始 Kenney Furniture Kit 许可的 CC0 叠放式洗衣烘干机。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/furniture-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/furniture-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/furniture-kit/washerDryerStacked.glb',
  }),
  asset({
    id: 'modern-ceiling-fan',
    name: 'Modern Ceiling Fan',
    category: '家居',
    path: 'vendor/kenney/furniture-kit/Models/GLTF format/ceilingFan.glb',
    size: 15284,
    license: 'CC0 1.0',
    attribution: 'Kenney / Furniture Kit；CC0 无强制署名。',
    riskNote: '通用低多边形三叶吊扇，无可见文字、Logo 或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2018-10-20',
    description: 'GitHub 固定镜像中保留原始 Kenney Furniture Kit 许可的 CC0 现代吊扇。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/furniture-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/furniture-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/furniture-kit/ceilingFan.glb',
  }),
  asset({
    id: 'design-lounge-sofa',
    name: 'Design Lounge Sofa',
    category: '家居',
    path: 'vendor/kenney/furniture-kit/Models/GLTF format/loungeDesignSofa.glb',
    size: 9128,
    license: 'CC0 1.0',
    attribution: 'Kenney / Furniture Kit；CC0 无强制署名。',
    riskNote: '通用低多边形双人休闲沙发，无可见文字、Logo 或现实品牌元素。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2018-10-20',
    description: 'GitHub 固定镜像中保留原始 Kenney Furniture Kit 许可的 CC0 设计休闲沙发。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/furniture-kit/License.txt',
    originalSourceUrl: 'https://kenney.nl/assets/furniture-kit',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/furniture-kit/loungeDesignSofa.glb',
  }),
  asset({
    id: 'race-finish-gantry',
    name: 'Race Finish Gantry',
    category: '场景',
    path: 'models/track-finish.glb',
    size: 24544,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit Racing 3D 模型以 CC0 发布。',
    riskNote: '通用低多边形赛道组件，无可见品牌标识。',
    repo: 'KenneyNL/Starter-Kit-Racing',
    branchName: 'main',
    commit: 'f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc',
    stars: 366,
    updated: '2026-03-31',
    description: 'Kenney Starter Kit Racing 中的 CC0 赛道终点门架。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-Racing/blob/f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-racing/f5241ebdf00c25bc951bf4fdb7950bb1b78b4bcc/race-finish-gantry.glb',
  }),
  asset({
    id: 'flying-mechanical-drone',
    name: 'Flying Mechanical Drone',
    category: '机械',
    path: 'models/enemy-flying.glb',
    size: 57828,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit FPS 3D 模型以 CC0 发布。',
    riskNote: '原文件名带有游戏敌人语义；模型本身为无品牌的通用低多边形悬浮无人机。',
    repo: 'KenneyNL/Starter-Kit-FPS',
    branchName: 'main',
    commit: '185fd2326d74a5cf858cffc616f87cf9696f9cc0',
    stars: 0,
    updated: '2026',
    description: 'Kenney Starter Kit FPS 中的 CC0 低多边形机械无人机。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-FPS/blob/185fd2326d74a5cf858cffc616f87cf9696f9cc0/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-fps/185fd2326d74a5cf858cffc616f87cf9696f9cc0/flying-mechanical-drone.glb',
  }),
  asset({
    id: 'falling-mechanism-platform',
    name: 'Falling Mechanism Platform',
    category: '机械',
    path: 'models/platform-falling.glb',
    size: 17048,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit 3D Platformer 3D 模型以 CC0 发布。',
    riskNote: '模型本身为静态低多边形机关平台，不包含坠落行为或品牌元素。',
    repo: 'KenneyNL/Starter-Kit-3D-Platformer',
    branchName: 'main',
    commit: '3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0',
    stars: 0,
    updated: '2026-03-12',
    description: 'Kenney Starter Kit 3D Platformer 中的 CC0 机关平台构件。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-3D-Platformer/blob/3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-3d-platformer/3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0/falling-mechanism-platform.glb',
  }),
  asset({
    id: 'platformer-robot',
    name: 'Platformer Robot Character',
    category: '角色',
    path: 'models/character.glb',
    size: 87624,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit 3D Platformer 3D 模型以 CC0 发布。',
    riskNote: '通用低多边形机器人角色，含待机、行走和跳跃等 4 个动画，无品牌元素。',
    repo: 'KenneyNL/Starter-Kit-3D-Platformer',
    branchName: 'main',
    commit: '3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0',
    stars: 0,
    updated: '2026-03-12',
    description: 'Kenney Starter Kit 3D Platformer 中的 CC0 动画机器人角色。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-3D-Platformer/blob/3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-3d-platformer/3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0/platformer-robot.glb',
  }),
  asset({
    id: 'coin-question-block',
    name: 'Coin Question Block',
    category: '产品',
    path: 'models/block-coin.glb',
    size: 66092,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit 3D Platformer 3D 模型以 CC0 发布。',
    riskNote: '通用低多边形游戏道具，无文字、Logo 或第三方品牌元素。',
    repo: 'KenneyNL/Starter-Kit-3D-Platformer',
    branchName: 'main',
    commit: '3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0',
    stars: 0,
    updated: '2026-03-12',
    description: 'Kenney Starter Kit 3D Platformer 中的 CC0 金币问号方块道具。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-3D-Platformer/blob/3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-3d-platformer/3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0/coin-question-block.glb',
  }),
  asset({
    id: 'round-grass-platform',
    name: 'Large Round Grass Platform',
    category: '场景',
    path: 'models/platform-grass-large-round.glb',
    size: 11316,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit 3D Platformer 3D 模型以 CC0 发布。',
    riskNote: '通用低多边形草地场景模块，无文字、Logo 或品牌元素。',
    repo: 'KenneyNL/Starter-Kit-3D-Platformer',
    branchName: 'main',
    commit: '3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0',
    stars: 0,
    updated: '2026-03-12',
    description: 'Kenney Starter Kit 3D Platformer 中的 CC0 圆形草地平台。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-3D-Platformer/blob/3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-3d-platformer/3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0/round-grass-platform.glb',
  }),
  asset({
    id: 'armchair-with-pillows',
    name: 'Armchair with Pillows',
    category: '家居',
    path: 'addons/kaykit_furniture_bits/Assets/gltf/armchair_pillows.gltf',
    size: 39061,
    license: 'CC0 1.0',
    attribution: 'Kay Lousberg / KayKit；CC0 无强制署名。',
    riskNote: '通用低多边形家具，无文字、Logo 或品牌元素；完整包包含 glTF、BIN 与共享纹理。',
    repo: 'KayKit-Game-Assets/KayKit-Furniture-Bits-1.0',
    branchName: 'main',
    commit: '96d5930a8dbdb363409bbc2d3341718b00e17c9c',
    stars: 0,
    updated: '2023-09-16',
    description: 'KayKit Furniture Bits 中带双靠枕的 CC0 低多边形扶手椅。',
    licenseUrl: 'https://github.com/KayKit-Game-Assets/KayKit-Furniture-Bits-1.0/blob/96d5930a8dbdb363409bbc2d3341718b00e17c9c/LICENSE.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-furniture-bits-1.0/96d5930a8dbdb363409bbc2d3341718b00e17c9c/armchair-with-pillows/armchair_pillows.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-furniture-bits-1.0/96d5930a8dbdb363409bbc2d3341718b00e17c9c/armchair-with-pillows/armchair-with-pillows-complete.zip',
  }),
  asset({
    id: 'standing-lamp',
    name: 'Standing Lamp',
    category: '灯具',
    path: 'addons/kaykit_furniture_bits/Assets/gltf/lamp_standing.gltf',
    size: 30287,
    license: 'CC0 1.0',
    attribution: 'Kay Lousberg / KayKit；CC0 无强制署名。',
    riskNote: '通用低多边形落地灯，无文字、Logo 或品牌元素；完整包包含 glTF、BIN 与共享纹理。',
    repo: 'KayKit-Game-Assets/KayKit-Furniture-Bits-1.0',
    branchName: 'main',
    commit: '96d5930a8dbdb363409bbc2d3341718b00e17c9c',
    stars: 0,
    updated: '2023-09-16',
    description: 'KayKit Furniture Bits 中的 CC0 低多边形落地灯。',
    licenseUrl: 'https://github.com/KayKit-Game-Assets/KayKit-Furniture-Bits-1.0/blob/96d5930a8dbdb363409bbc2d3341718b00e17c9c/LICENSE.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-furniture-bits-1.0/96d5930a8dbdb363409bbc2d3341718b00e17c9c/standing-lamp/lamp_standing.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-furniture-bits-1.0/96d5930a8dbdb363409bbc2d3341718b00e17c9c/standing-lamp/standing-lamp-complete.zip',
  }),
  asset({
    id: 'space-mining-drill',
    name: 'Space Mining Drill',
    category: '机械',
    path: 'addons/kaykit_space_base_bits/Assets/gltf/drill_structure.gltf',
    size: 99088,
    license: 'CC0 1.0',
    attribution: 'Kay Lousberg / KayKit；CC0 无强制署名。',
    riskNote: '虚构的通用低多边形钻机，无文字、Logo 或品牌元素；完整包包含 glTF、BIN 与共享纹理。',
    repo: 'KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0',
    branchName: 'main',
    commit: '6dfbcac9927d06283752c4defd4882cfe0d29666',
    stars: 0,
    updated: '2023-09-16',
    description: 'KayKit Space Base Bits 中的 CC0 虚构太空采矿钻机。',
    licenseUrl: 'https://github.com/KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0/blob/6dfbcac9927d06283752c4defd4882cfe0d29666/LICENSE.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/space-mining-drill/drill_structure.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/space-mining-drill/space-mining-drill-complete.zip',
  }),
  asset({
    id: 'primary-ion-drive',
    name: 'Primary Ion Drive',
    category: '机械',
    path: 'examples/models/gltf/PrimaryIonDrive.glb',
    size: 5800408,
    license: 'CC BY 4.0',
    attribution: '“Primary Ion Drive ///” by indierocktopus（Sketchfab），使用时需保留 CC BY 4.0 署名与来源。',
    riskNote: '固定 GLB 的 asset.extras 内嵌作者、原始来源和 CC BY 4.0；虚构装置，无可见现实品牌或 Logo。',
    repo: 'mrdoob/three.js',
    branchName: 'dev',
    commit: '34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8',
    stars: 110000,
    updated: '2026-07-20',
    description: 'Three.js 官方样例仓库中的高细节动画离子推进器。',
    licenseUrl: 'https://github.com/mrdoob/three.js/blob/34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8/examples/models/gltf/PrimaryIonDrive.glb',
    originalSourceUrl: 'https://sketchfab.com/models/d3f50a66fee74c6588dd9bc92f7fe7b3',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/mrdoob/three.js/34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8/primary-ion-drive.glb',
  }),
  asset({
    id: 'city-sedan',
    name: 'City Sedan',
    category: '汽车',
    path: 'addons/kaykit_city_builder_bits/Assets/gltf/car_sedan.gltf',
    size: 86145,
    license: 'CC0 1.0',
    attribution: 'Kay Lousberg / KayKit；CC0 无强制署名。',
    riskNote: '无品牌低多边形城市轿车，不代表任何真实厂牌；完整包包含 glTF、BIN 与共享纹理。',
    repo: 'KayKit-Game-Assets/KayKit-City-Builder-Bits-1.0',
    branchName: 'main',
    commit: '63976910ca04d16f0fc531b9c614244be8128713',
    stars: 0,
    updated: '2023-09-16',
    description: 'KayKit City Builder Bits 中的 CC0 无品牌低多边形城市轿车。',
    licenseUrl: 'https://github.com/KayKit-Game-Assets/KayKit-City-Builder-Bits-1.0/blob/63976910ca04d16f0fc531b9c614244be8128713/LICENSE.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-city-builder-bits-1.0/63976910ca04d16f0fc531b9c614244be8128713/city-sedan/car_sedan.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-city-builder-bits-1.0/63976910ca04d16f0fc531b9c614244be8128713/city-sedan/city-sedan-complete.zip',
  }),
  asset({
    id: 'freestanding-oven',
    name: 'Freestanding Oven',
    category: '数码',
    path: 'addons/kaykit_restaurant_bits/Assets/gltf/oven.gltf',
    size: 60708,
    license: 'CC0 1.0',
    attribution: 'Kay Lousberg / KayKit；CC0 无强制署名。',
    riskNote: '通用风格化家电，无文字、Logo 或品牌元素；完整包包含 glTF、BIN 与共享纹理。',
    repo: 'KayKit-Game-Assets/KayKit-Restaurant-Bits-1.0',
    branchName: 'main',
    commit: '153c8a7535b48237854cb54ff6890679f8c574d1',
    stars: 0,
    updated: '2023-09-29',
    description: 'KayKit Restaurant Bits 中的 CC0 低多边形独立烤箱。',
    licenseUrl: 'https://github.com/KayKit-Game-Assets/KayKit-Restaurant-Bits-1.0/blob/153c8a7535b48237854cb54ff6890679f8c574d1/LICENSE.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-restaurant-bits-1.0/153c8a7535b48237854cb54ff6890679f8c574d1/freestanding-oven/oven.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-restaurant-bits-1.0/153c8a7535b48237854cb54ff6890679f8c574d1/freestanding-oven/freestanding-oven-complete.zip',
  }),
  asset({
    id: 'tall-wind-turbine',
    name: 'Tall Wind Turbine',
    category: '机械',
    path: 'addons/kaykit_space_base_bits/Assets/gltf/windturbine_tall.gltf',
    size: 60821,
    license: 'CC0 1.0',
    attribution: 'Kay Lousberg / KayKit；CC0 无强制署名。',
    riskNote: '通用低多边形工程设施，无文字、Logo 或品牌元素；完整包包含 glTF、BIN 与共享纹理。',
    repo: 'KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0',
    branchName: 'main',
    commit: '6dfbcac9927d06283752c4defd4882cfe0d29666',
    stars: 0,
    updated: '2023-09-16',
    description: 'KayKit Space Base Bits 中的 CC0 高塔风力发电机。',
    licenseUrl: 'https://github.com/KayKit-Game-Assets/KayKit-Space-Base-Bits-1.0/blob/6dfbcac9927d06283752c4defd4882cfe0d29666/LICENSE.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/tall-wind-turbine/windturbine_tall.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kaykit-game-assets/kaykit-space-base-bits-1.0/6dfbcac9927d06283752c4defd4882cfe0d29666/tall-wind-turbine/tall-wind-turbine-complete.zip',
  }),
  asset({
    id: 'city-garage',
    name: 'City Garage',
    category: '场景',
    path: 'models/building-garage.glb',
    size: 19204,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit City Builder 3D 模型以 CC0 发布。',
    riskNote: '低多边形城市建筑，无品牌标识。',
    repo: 'KenneyNL/Starter-Kit-City-Builder',
    branchName: 'main',
    commit: '4535092b740b378b700efd9df9e27a631815b84a',
    stars: 0,
    updated: '2026-07-18',
    description: 'Kenney Starter Kit City Builder 中的 CC0 城市建筑素材。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-City-Builder/blob/4535092b740b378b700efd9df9e27a631815b84a/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-city-builder/4535092b740b378b700efd9df9e27a631815b84a/city-garage.glb',
  }),
  asset({
    id: 'city-house',
    name: 'Small City House',
    category: '家居',
    path: 'models/building-small-c.glb',
    size: 70088,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit City Builder 3D 模型以 CC0 发布。',
    riskNote: '低多边形城市住宅，无品牌标识。',
    repo: 'KenneyNL/Starter-Kit-City-Builder',
    branchName: 'main',
    commit: '4535092b740b378b700efd9df9e27a631815b84a',
    stars: 0,
    updated: '2026-07-18',
    description: 'Kenney Starter Kit City Builder 中的 CC0 城市住宅素材。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-City-Builder/blob/4535092b740b378b700efd9df9e27a631815b84a/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-city-builder/4535092b740b378b700efd9df9e27a631815b84a/city-house.glb',
  }),
  asset({
    id: 'city-fountain',
    name: 'City Fountain',
    category: '场景',
    path: 'models/pavement-fountain.glb',
    size: 14076,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit City Builder 3D 模型以 CC0 发布。',
    riskNote: '低多边形城市喷泉，无品牌标识。',
    repo: 'KenneyNL/Starter-Kit-City-Builder',
    branchName: 'main',
    commit: '4535092b740b378b700efd9df9e27a631815b84a',
    stars: 0,
    updated: '2026-07-18',
    description: 'Kenney Starter Kit City Builder 中的 CC0 城市装饰素材。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-City-Builder/blob/4535092b740b378b700efd9df9e27a631815b84a/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-city-builder/4535092b740b378b700efd9df9e27a631815b84a/city-fountain.glb',
  }),
  asset({
    id: 'road-lightposts',
    name: 'Streetlight Road Segment',
    category: '场景',
    path: 'models/road-straight-lightposts.glb',
    size: 18216,
    license: 'CC0 1.0',
    attribution: 'Kenney，Starter Kit City Builder 3D 模型以 CC0 发布。',
    riskNote: '路灯与直道路面合并为单个网格，适合作为场景组件而非独立灯具。',
    repo: 'KenneyNL/Starter-Kit-City-Builder',
    branchName: 'main',
    commit: '4535092b740b378b700efd9df9e27a631815b84a',
    stars: 0,
    updated: '2026-07-18',
    description: 'Kenney Starter Kit City Builder 中的 CC0 双路灯直道路段。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-City-Builder/blob/4535092b740b378b700efd9df9e27a631815b84a/README.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-city-builder/4535092b740b378b700efd9df9e27a631815b84a/road-lightposts.glb',
  }),
  asset({
    id: 'arena-statue',
    name: 'Arena Statue',
    category: '场景',
    path: 'sample/Mini Arena/Models/GLB format/statue.glb',
    size: 51012,
    license: 'CC0 1.0',
    attribution: 'Kenney / Tony Schär，Mini Arena 3D 模型以 CC0 发布。',
    riskNote: '通用低多边形雕像，无文字、Logo 或品牌节点。',
    repo: 'KenneyNL/Starter-Kit-Basic-Scene',
    branchName: 'main',
    commit: 'a6927e66ff8dd8e173660ce4825abe773c65f683',
    stars: 0,
    updated: '2026-03-12',
    description: 'Kenney Mini Arena 中的 CC0 低多边形场景雕像。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-Basic-Scene/blob/a6927e66ff8dd8e173660ce4825abe773c65f683/sample/Mini%20Arena/License.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-basic-scene/a6927e66ff8dd8e173660ce4825abe773c65f683/arena-statue.glb',
  }),
  asset({
    id: 'arena-wall-gate',
    name: 'Arena Wall Gate',
    category: '场景',
    path: 'sample/Mini Arena/Models/GLB format/wall-gate.glb',
    size: 31064,
    license: 'CC0 1.0',
    attribution: 'Kenney / Tony Schär，Mini Arena 3D 模型以 CC0 发布。',
    riskNote: '通用竞技场建筑构件，无文字、Logo 或品牌元素。',
    repo: 'KenneyNL/Starter-Kit-Basic-Scene',
    branchName: 'main',
    commit: 'a6927e66ff8dd8e173660ce4825abe773c65f683',
    stars: 0,
    updated: '2026-03-12',
    description: 'Kenney Mini Arena 中的 CC0 低多边形建筑构件。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-Basic-Scene/blob/a6927e66ff8dd8e173660ce4825abe773c65f683/sample/Mini%20Arena/License.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-basic-scene/a6927e66ff8dd8e173660ce4825abe773c65f683/arena-wall-gate.glb',
  }),
  asset({
    id: 'low-poly-pine-tree',
    name: 'Low-poly Pine Tree',
    category: '场景',
    path: 'sample/Mini Arena/Models/GLB format/tree.glb',
    size: 34164,
    license: 'CC0 1.0',
    attribution: 'Kenney / Tony Schär，Mini Arena 3D 模型以 CC0 发布。',
    riskNote: '通用自然场景资产，无文字、Logo 或品牌元素。',
    repo: 'KenneyNL/Starter-Kit-Basic-Scene',
    branchName: 'main',
    commit: 'a6927e66ff8dd8e173660ce4825abe773c65f683',
    stars: 0,
    updated: '2026-03-12',
    description: 'Kenney Mini Arena 中的 CC0 低多边形自然场景素材。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-Basic-Scene/blob/a6927e66ff8dd8e173660ce4825abe773c65f683/sample/Mini%20Arena/License.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-basic-scene/a6927e66ff8dd8e173660ce4825abe773c65f683/low-poly-pine-tree.glb',
  }),
  asset({
    id: 'arena-trophy',
    name: 'Arena Trophy',
    category: '产品',
    path: 'sample/Mini Arena/Models/GLB format/trophy.glb',
    size: 23752,
    license: 'CC0 1.0',
    attribution: 'Kenney / Tony Schär，Mini Arena 3D 模型以 CC0 发布。',
    riskNote: '通用低多边形奖杯，无文字、Logo 或品牌元素。',
    repo: 'KenneyNL/Starter-Kit-Basic-Scene',
    branchName: 'main',
    commit: 'a6927e66ff8dd8e173660ce4825abe773c65f683',
    stars: 0,
    updated: '2026-03-12',
    description: 'Kenney Mini Arena 中的 CC0 低多边形竞技奖杯。',
    licenseUrl: 'https://github.com/KenneyNL/Starter-Kit-Basic-Scene/blob/a6927e66ff8dd8e173660ce4825abe773c65f683/sample/Mini%20Arena/License.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/kenneynl/starter-kit-basic-scene/a6927e66ff8dd8e173660ce4825abe773c65f683/arena-trophy.glb',
  }),
  asset({
    id: 'antique-camera',
    name: 'Antique Camera',
    category: '相机',
    path: 'Models/AntiqueCamera/glTF-Binary/AntiqueCamera.glb',
    size: 17540348,
    license: 'CC0 1.0 + 商标说明',
    attribution: 'Maximillan Kamps / UX3D；模型以 CC0 发布，三脚架含 UX3D 标志。',
    riskNote: '逐资产许可另列 UX3D Trademark or Logo；保留 GitHub 来源，不迁移到本库 TOS。',
  }),
  asset({
    id: 'steampunk-camera',
    name: 'Steampunk Camera',
    category: '相机',
    path: 'examples/models/gltf/steampunk_camera.glb',
    size: 3946424,
    license: 'CC BY 4.0',
    attribution: '“Steampunk Camera” by lumoize（Sketchfab），使用时需保留 CC BY 4.0 署名与来源。',
    riskNote: '固定 GLB 的 asset.extras 内嵌作者、原始来源和 CC BY 4.0；未发现可见品牌或 Logo。需要支持 EXT_texture_webp。',
    repo: 'mrdoob/three.js',
    branchName: 'dev',
    commit: '34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8',
    stars: 110000,
    updated: '2026-07-20',
    description: 'Three.js 官方样例仓库中的高细节蒸汽朋克相机。',
    licenseUrl: 'https://github.com/mrdoob/three.js/blob/34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8/examples/models/gltf/steampunk_camera.glb',
    originalSourceUrl: 'https://sketchfab.com/3d-models/steampunk-camera-a2210a0ba6834141af3bf83ee1e03f07',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/mrdoob/three.js/34a5b176cc96f56441c1a8f8c0b5acd17a56e8c8/steampunk-camera.glb',
  }),
  asset({
    id: 'chronograph-watch',
    name: 'Chronograph Watch',
    category: '穿戴',
    path: 'Models/ChronographWatch/glTF-Binary/ChronographWatch.glb',
    size: 7446368,
    license: 'CC BY 4.0 + 商标说明',
    attribution: 'Eric Chadwick / Darmstadt Graphics Group；基于 graphiccompressor 的 Chronograph Watch Mudmaster。',
    riskNote: '表盘含 Khronos、3D Commerce 与 DGG 标志；保留 GitHub 来源，不迁移到本库 TOS。',
  }),
  asset({
    id: 'boom-box',
    name: 'Boom Box',
    category: '数码',
    path: 'Models/BoomBox/glTF-Binary/BoomBox.glb',
    size: 10614184,
    license: 'CC0 1.0',
    attribution: 'Khronos glTF Sample Assets / Public。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/boom-box.glb',
  }),
  asset({
    id: 'vintage-television',
    name: 'Vintage Television',
    category: '数码',
    path: 'vendor/kenney/furniture-kit/Models/GLTF format/televisionVintage.glb',
    size: 19392,
    license: 'CC0 1.0',
    attribution: 'Kenney / Furniture Kit；CC0 无强制署名。',
    riskNote: '通用低多边形复古电视造型，无纹理、文字或 Logo；CC0 不涉及商标授权。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2026-07-13',
    description: 'GitHub 固定镜像中保留原始 Kenney Furniture Kit 许可的 CC0 复古电视机。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/furniture-kit/License.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vintage-television.glb',
  }),
  asset({
    id: 'countertop-coffee-machine',
    name: 'Countertop Coffee Machine',
    category: '数码',
    path: 'vendor/kenney/furniture-kit/Models/GLTF format/kitchenCoffeeMachine.glb',
    size: 13332,
    license: 'CC0 1.0',
    attribution: 'Kenney / Furniture Kit；CC0 无强制署名。',
    riskNote: '通用低多边形台式咖啡机与杯子，无纹理、文字或 Logo；CC0 不涉及商标授权。',
    repo: 'subtiliorars-sys/game-3d-assets',
    branchName: 'main',
    commit: 'b8984ce96e222b5d5ba5a7a17b9a5faa3be38995',
    stars: 0,
    updated: '2026-07-13',
    description: 'GitHub 固定镜像中保留原始 Kenney Furniture Kit 许可的 CC0 台式咖啡机与杯子。',
    licenseUrl: 'https://github.com/subtiliorars-sys/game-3d-assets/blob/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/vendor/kenney/furniture-kit/License.txt',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/subtiliorars-sys/game-3d-assets/b8984ce96e222b5d5ba5a7a17b9a5faa3be38995/countertop-coffee-machine.glb',
  }),
  asset({
    id: 'commercial-refrigerator',
    name: 'Commercial Refrigerator',
    category: '机械',
    path: 'Models/CommercialRefrigerator/glTF-Binary/CommercialRefrigerator.glb',
    size: 10131180,
    license: 'CC BY 4.0',
    attribution: '基于 Sean Thomas 的 Commercial Fridge。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/commercial-refrigerator.glb',
  }),
  asset({
    id: 'water-bottle',
    name: 'Water Bottle',
    category: '产品',
    path: 'Models/WaterBottle/glTF-Binary/WaterBottle.glb',
    size: 8966700,
    license: 'CC0 1.0',
    attribution: 'Microsoft，以 CC0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/water-bottle.glb',
  }),
  asset({
    id: 'materials-variants-shoe',
    name: 'Materials Variants Shoe',
    category: '穿戴',
    path: 'Models/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb',
    size: 7833592,
    license: 'CC BY 4.0',
    attribution: 'Shopify；包含 KHR_materials_variants。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/materials-variants-shoe.glb',
  }),
  asset({
    id: 'cesium-milk-truck',
    name: 'Cesium Milk Truck',
    category: '汽车',
    path: 'Models/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb',
    size: 369980,
    license: 'LicenseRef-CC-BY-TM + Cesium 商标',
    attribution: 'Cesium；使用时需保留署名并注意商标限制。',
    riskNote: '上游采用无公开条款链接的自定义 LicenseRef-CC-BY-TM，并另列 Cesium 商标；保留 GitHub 来源，不迁移到本库 TOS。',
  }),
  asset({
    id: 'sunglasses-khronos',
    name: 'Sunglasses',
    category: '穿戴',
    path: 'Models/SunglassesKhronos/glTF-Binary/SunglassesKhronos.glb',
    size: 371188,
    license: 'CC BY 4.0 + 商标说明',
    attribution: 'Eric Chadwick / DGG；含 Khronos 与 3D Commerce 标志。',
    riskNote: '耳钩纹理含 Khronos 标志，且另列 3D Commerce 标志；保留 GitHub 来源，不迁移到本库 TOS。',
  }),
  asset({
    id: 'anisotropy-barn-lamp',
    name: 'Anisotropy Barn Lamp',
    category: '灯具',
    path: 'Models/AnisotropyBarnLamp/glTF-Binary/AnisotropyBarnLamp.glb',
    size: 7833440,
    license: 'CC BY 4.0',
    attribution: 'Eric Chadwick / Wayfair，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/anisotropy-barn-lamp.glb',
  }),
  asset({
    id: 'iridescence-lamp',
    name: 'Iridescence Lamp',
    category: '灯具',
    path: 'Models/IridescenceLamp/glTF-Binary/IridescenceLamp.glb',
    size: 4083912,
    license: 'CC BY 4.0',
    attribution: 'Eric Chadwick / Wayfair，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/iridescence-lamp.glb',
  }),
  asset({
    id: 'punctual-light-lamp',
    name: 'Punctual Light Lamp',
    category: '灯具',
    path: 'Models/LightsPunctualLamp/glTF-Binary/LightsPunctualLamp.glb',
    size: 4341320,
    license: 'CC BY 4.0',
    attribution: 'DGG，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/punctual-light-lamp.glb',
  }),
  asset({
    id: 'stained-glass-lamp',
    name: 'Stained Glass Lamp',
    category: '灯具',
    path: 'Models/StainedGlassLamp/glTF-JPG-PNG/StainedGlassLamp.gltf',
    size: 11095469,
    license: 'CC BY 4.0',
    attribution: 'Stained Glass Lamp © 2021 Eric Chadwick / Wayfair，使用时需保留 CC BY 4.0 署名。',
    riskNote: '真实电商产品参考模型；避免暗示 Wayfair 对改造版本或发布方背书。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/stained-glass-lamp/StainedGlassLamp.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/stained-glass-lamp/StainedGlassLamp-complete.zip',
  }),
  asset({
    id: 'lantern',
    name: 'Lantern',
    category: '灯具',
    path: 'Models/Lantern/glTF-Binary/Lantern.glb',
    size: 9564264,
    license: 'CC0 1.0',
    attribution: 'sbtron / Microsoft；由 Frank Galligan 转换。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/lantern.glb',
  }),
  asset({
    id: 'chair-damask',
    name: 'Damask Purple Gold Chair',
    category: '家居',
    path: 'Models/ChairDamaskPurplegold/glTF-Binary/ChairDamaskPurplegold.glb',
    size: 2028924,
    license: 'CC BY 4.0',
    attribution: 'Eric Chadwick / Wayfair，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/chair-damask.glb',
  }),
  asset({
    id: 'glam-velvet-sofa',
    name: 'Glam Velvet Sofa',
    category: '家居',
    path: 'Models/GlamVelvetSofa/glTF-Binary/GlamVelvetSofa.glb',
    size: 3149844,
    license: 'CC BY 4.0',
    attribution: 'Eric Chadwick / Wayfair，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/glam-velvet-sofa.glb',
  }),
  asset({
    id: 'sheen-chair',
    name: 'Sheen Chair',
    category: '家居',
    path: 'Models/SheenChair/glTF-Binary/SheenChair.glb',
    size: 4125648,
    license: 'CC0 1.0',
    attribution: 'Eric Chadwick / Wayfair，以 CC0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/sheen-chair.glb',
  }),
  asset({
    id: 'wood-leather-sofa',
    name: 'Wood Leather Sofa',
    category: '家居',
    path: 'Models/SheenWoodLeatherSofa/glTF-Binary/SheenWoodLeatherSofa.glb',
    size: 10107912,
    license: 'CC BY 4.0',
    attribution: '原始资产 CC0，改进部分由 Eric Chadwick / DGG 以 CC BY 4.0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/wood-leather-sofa.glb',
  }),
  asset({
    id: 'silk-pouf',
    name: 'Specular Silk Pouf',
    category: '家居',
    path: 'Models/SpecularSilkPouf/glTF-Binary/SpecularSilkPouf.glb',
    size: 4632512,
    license: 'CC BY 4.0',
    attribution: 'Eric Chadwick / Wayfair，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/silk-pouf.glb',
  }),
  asset({
    id: 'glass-vase-flowers',
    name: 'Glass Vase & Flowers',
    category: '家居',
    path: 'Models/GlassVaseFlowers/glTF-Binary/GlassVaseFlowers.glb',
    size: 1819824,
    license: 'CC0 1.0',
    attribution: 'Eric Chadwick / Rico Cilliers，以 CC0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/glass-vase-flowers.glb',
  }),
  asset({
    id: 'hurricane-candle-holder',
    name: 'Hurricane Candle Holder',
    category: '家居',
    path: 'Models/GlassHurricaneCandleHolder/glTF-Binary/GlassHurricaneCandleHolder.glb',
    size: 2705400,
    license: 'CC BY 4.0 + 商标说明',
    attribution: 'Eric Chadwick / Wayfair；含 Khronos/glTF 标志。',
    riskNote: '逐资产许可另列 Khronos 与 glTF 标志；商标权不随 CC BY 4.0 授予，不迁移到本库 TOS。',
  }),
  asset({
    id: 'broken-window',
    name: 'Glass Broken Window',
    category: '家居',
    path: 'Models/GlassBrokenWindow/glTF-Binary/GlassBrokenWindow.glb',
    size: 1076624,
    license: 'CC BY 4.0',
    attribution: 'Eric Chadwick / Wayfair，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/broken-window.glb',
  }),
  asset({
    id: 'transmission-plant',
    name: 'Transmission Plant',
    category: '家居',
    path: 'Models/DiffuseTransmissionPlant/glTF-Binary/DiffuseTransmissionPlant.glb',
    size: 5759100,
    license: 'CC BY 4.0',
    attribution: '原始资产 CC0，材质和动画由 Eric Chadwick / DGG 以 CC BY 4.0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/transmission-plant.glb',
  }),
  asset({
    id: 'corset',
    name: 'Corset',
    category: '穿戴',
    path: 'Models/Corset/glTF-Binary/Corset.glb',
    size: 13491364,
    license: 'CC0 1.0',
    attribution: 'Microsoft / UX3D，以 CC0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/corset.glb',
  }),
  asset({
    id: 'avocado',
    name: 'Avocado',
    category: '产品',
    path: 'Models/Avocado/glTF-Binary/Avocado.glb',
    size: 8110040,
    license: 'CC0 1.0',
    attribution: 'Microsoft，以 CC0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/avocado.glb',
  }),
  asset({
    id: 'barramundi-fish',
    name: 'Barramundi Fish',
    category: '产品',
    path: 'Models/BarramundiFish/glTF-Binary/BarramundiFish.glb',
    size: 12488144,
    license: 'CC0 1.0',
    attribution: 'Microsoft，以 CC0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/barramundi-fish.glb',
  }),
  asset({
    id: 'transmission-teacup',
    name: 'Transmission Teacup',
    category: '产品',
    path: 'Models/DiffuseTransmissionTeacup/glTF-Binary/DiffuseTransmissionTeacup.glb',
    size: 4795028,
    license: 'CC0 1.0',
    attribution: 'Poly Haven / Eric Chadwick，以 CC0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/transmission-teacup.glb',
  }),
  asset({
    id: 'iridescent-dish',
    name: 'Iridescent Dish With Olives',
    category: '产品',
    path: 'Models/IridescentDishWithOlives/glTF-Binary/IridescentDishWithOlives.glb',
    size: 5742828,
    license: 'CC BY 4.0',
    attribution: '© 2020 Wayfair, LLC；Eric Chadwick，使用时需署名。',
    riskNote: '逐资产 LICENSE 与 metadata 仅列 CC BY 4.0，未列 Logo 或商标附加条款。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/iridescent-dish.glb',
  }),
  asset({
    id: 'iridescence-abalone',
    name: 'Iridescence Abalone',
    category: '家居',
    path: 'Models/IridescenceAbalone/glTF-Binary/IridescenceAbalone.glb',
    size: 9300744,
    license: 'CC BY 4.0',
    attribution: 'Abby Crawford（模型）与 Eric Chadwick（材质），使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/iridescence-abalone.glb',
  }),
  asset({
    id: 'mosquito-in-amber',
    name: 'Mosquito In Amber',
    category: '产品',
    path: 'Models/MosquitoInAmber/glTF-Binary/MosquitoInAmber.glb',
    size: 24229904,
    license: 'CC BY 4.0',
    attribution: 'Loïc Norgeot（模型）、Geoffrey Marchal（蚊虫扫描）与 Sketchfab（实时折射版本），使用时需保留 CC BY 4.0 署名。',
  }),
  asset({
    id: 'a-beautiful-game',
    name: 'A Beautiful Game',
    category: '家居',
    path: 'Models/ABeautifulGame/glTF-Binary-KTX-ETC1S-Draco/ABeautifulGame.glb',
    size: 12105252,
    license: 'CC BY 4.0',
    attribution: 'MaterialX Project / ASWF 与 Ed Mackey，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/a-beautiful-game.glb',
  }),
  asset({
    id: 'sheen-cloth',
    name: 'Sheen Cloth',
    category: '材质',
    path: 'Models/SheenCloth/glTF/SheenCloth.gltf',
    size: 4180438,
    license: 'CC0 1.0',
    attribution: 'Microsoft，2020 年以 CC0 1.0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/sheen-cloth/SheenCloth.gltf',
    packageUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/sheen-cloth/SheenCloth-complete.zip',
  }),
  asset({
    id: 'carbon-fibre',
    name: 'Carbon Fibre',
    category: '材质',
    path: 'Models/CarbonFibre/glTF-Binary/CarbonFibre.glb',
    size: 429880,
    license: 'CC BY 4.0',
    attribution: 'Eric Chadwick / Wayfair，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/carbon-fibre.glb',
  }),
  asset({
    id: 'clear-coat-car-paint',
    name: 'Clear Coat Car Paint',
    category: '材质',
    path: 'Models/ClearCoatCarPaint/glTF-Binary/ClearCoatCarPaint.glb',
    size: 116948,
    license: 'CC0 1.0',
    attribution: 'Eric Chadwick，以 CC0 发布。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/clear-coat-car-paint.glb',
  }),
  asset({
    id: 'clearcoat-wicker',
    name: 'Clearcoat Wicker',
    category: '材质',
    path: 'Models/ClearcoatWicker/glTF-Binary/ClearcoatWicker.glb',
    size: 1299752,
    license: 'CC0 1.0',
    attribution: 'Eric Chadwick，2023 年以 CC0 发布。',
    riskNote: '用于展示清漆藤编表面的材质测试球，不是完整家具产品。',
    description: 'Khronos glTF Sample Assets 中的自包含清漆藤编材质球。',
    licenseUrl: 'https://github.com/KhronosGroup/glTF-Sample-Assets/blob/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/Models/ClearcoatWicker/LICENSE.md',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/clearcoat-wicker.glb',
  }),
  asset({
    id: 'usd-shader-ball',
    name: 'USD Shader Ball',
    category: '材质',
    path: 'Models/USDShaderBallForGltf/glTF-Binary/USDShaderBallForGltf.glb',
    size: 1319652,
    license: 'CC BY 4.0',
    attribution: 'Chris Rydalch、André Mazzone、Thomas Anagnostou 与 Eric Chadwick，使用时需署名。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/usd-shader-ball.glb',
  }),
  asset({
    id: 'fox',
    name: 'Animated Fox',
    category: '角色',
    path: 'Models/Fox/glTF-Binary/Fox.glb',
    size: 162852,
    license: 'CC BY 4.0 + CC0 1.0',
    attribution: 'PixelMannen（模型）、tomkranis（绑定与动画）、Asobo Studio / scurest（glTF 转换）。',
    tosUrl: 'https://magic-builder.tos-cn-beijing.volces.com/forge3d/models/khronos-gltf-sample-assets/2bac6f8c57bf471df0d2a1e8a8ec023c7801dddf/fox.glb',
  }),
  asset({
    id: 'pot-of-coals',
    name: 'Pot Of Coals',
    category: '场景',
    path: 'Models/PotOfCoals/glTF-Binary/PotOfCoals.glb',
    size: 4696240,
    license: 'CC BY 4.0 + 商标说明',
    attribution: 'Eric Chadwick / DGG；含 Khronos/glTF 标志。',
    riskNote: '铜盆浮雕包含 glTF、Khronos 与 DGG 标志；商标权不随 CC BY 4.0 授予，不迁移到本库 TOS。',
  }),
];

export const categories = ['全部', '汽车', '相机', '数码', '机械', '家居', '灯具', '穿戴', '产品', '材质', '场景', '角色'];

export const queryAliases = {
  汽车: 'car vehicle automotive',
  车: 'car vehicle automotive',
  相机: 'camera photography',
  摄像机: 'camera photography',
  数码: 'digital electronic device',
  零件: 'mechanical part industrial',
  机械: 'mechanical part industrial',
  家居: 'furniture chair sofa home',
  灯具: 'lamp lantern light',
  穿戴: 'wearable shoe watch glasses fashion',
  材质: 'material shader surface',
  场景: 'scene city environment',
  角色: 'character animal creature',
  产品: 'product configurator object',
  手表: 'watch product',
};
